[user]
<<<<<<< HEAD
player1_algorithm = "random"
=======
player1_algorithm = "human"
>>>>>>> 4c3736b9c0a79b7ff2aa781ca4016ef4f4ee0df5
player2_algorithm = "random"

[graphics]
graphics_enabled = true
update_interval = 100

[game]
board_width = 11
board_height = 11
